### ISSUE TITLE
如何处理自定义Config注入时，字段名与配置文件内字段名不同的情况

### ISSUE THREAD

**Issue by DwGoing** [alibaba/IOC-golang#174]
```
// networks_config.go

package config

// +ioc:autowire=true
// +ioc:autowire:baseType=true
// +ioc:autowire:type=config
// +ioc:autowire:paramType=NetworksConfig
// +ioc:autowire:constructFunc=NewNetworksConfig
// +ioc:autowire:proxy:autoInjection=false

type NetworksConfig map[string]NetworkConfig

type NetworkConfig struct {
	Urls []string // 对应config.yaml中urlList字段
}

func (config *NetworksConfig) NewNetworksConfig(impl *NetworksConfig) (*NetworksConfig, error) {
	*impl = *config
	return impl, nil
}
```

```
// config.yaml
networks:
  mainnet:
    urlList:
      - https://xxx.io/
```
